TEXT_SCORE      = "PUNTOS: ";
TEXT_PAUSE      = "PAUSA";

HELP_TEXT_DESKTOP = "PRESIONA TU BARRA ESPACIADORA PARA INDICAR TU DIRRECION DE DISPARO!!";

HELP_TEXT_MOBILE  = "PRESIONA EL TOUCH DE TU TELEFONO PARA INDICAR LA DIRECCION DE TU DISPARO!!";

HELP_TEXT          = "GANARAS MAS PUNTOS SI APROVECHAS LA BARRA DE BONUS "+
                     "TUS PUNTOS SE AUMENTARAN UNIENDOLOS CON EL BONUS!";
